baseurl:/tianxinokok.github.io
#future: true
#permalink: /:title/
#url: http://tianxinokok.github.io
name: TT
author: tianxin
#qq: 505268168
email: tianxinokok@163.com
#beian: 
#cnzz:
sidebar_image:/source/img/index_left.jpg
pygments: true
safe: true
auto: true
github: tianxinokok
paginate: 20
#### Markdown Processors
markdown: kramdown

### Livere评论系统
Livere:
livere_uid: MTAyMC80MDQ4OS8xNzAxNg
#### Menu
menu:
  Home:/
  分类:/
  About:/about
###### css/js
source:/source

