baseurl:/tianxinokok.github.io
#future: true
#permalink: /:title/
#url: http://tianxinokok.github.io
name: TT
author: tianxin
#qq: 505268168
email: tianxinokok@163.com
#beian: 
#cnzz:
pygments: true
safe: true
auto: true 
github: tianxinokok
paginate: 20
#### Markdown Processors
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - tables
    - lax_spacing
    - with_toc_data


#highlighter: rouge
#truncate: true
#about: "TT"