baseurl:/tianxinokok.github.io
#future: true
#permalink: /:title/
#url: http://tianxinokok.github.io
name: TT
author: tianxin
#qq: 505268168
email: tianxinokok@163.com
#beian: 
#cnzz:
<<<<<<< HEAD
sidebar_image:/source/img/index_left.jpg
=======
>>>>>>> 5d4e353f4fdf785248196093a1ae0ec0a84c8221
pygments: true
safe: true
auto: true
github: tianxinokok
paginate: 20
#### Markdown Processors
markdown: kramdown
#### Menu
menu:
  Home:/
  分类:/
  About:/about
###### css/js
<<<<<<< HEAD
=======
source:/source
>>>>>>> 5d4e353f4fdf785248196093a1ae0ec0a84c8221

#highlighter: rouge
#truncate: true
#about: "TT"